### ISSUE TITLE
vscodeでECサイトの環境構築を行いたいな(docker-compose up --buildができない)

### ISSUE THREAD

**Issue by Potepan-sgtom** [Potepan-sgtom/rails_kadai4_hotel_service#4]
・やりたいこと
dockerの動作確認(正常にdockerのホームページ？を「http://localhost:3000/potepan/index.html」で閲覧できるようにする)

・現状把握
1.homebrewインストール、dockerインストールについては問題なく完了。その後git cloneでポテパンが用意したECサイトを作るためのファイルをvscodeに展開。
2.動作確認のためdocker-compose up --buildを入力。エラー
3.内容は把握できていないが、どうやらserver errorが出ているらしい。
↓
エラー内容
「Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error for http+docker://localhost/version: Internal Server Error ("b'dial unix docker.raw.sock: connect: no such file or directory'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 60, in project_from_options
  File "compose/cli/command.py", line 152, in get_project
  File "compose/cli/docker_client.py", line 41, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error for http+docker://localhost/version: Internal Server Error ("b'dial unix docker.raw.sock: connect: no such file or directory'")
[73907] Failed to execute script docker-compose」

・原因特定
1.ファイルについての指摘が多いため、おそらくどこかのファイルの記述を変更する必要がある。
↓
2.全く原因箇所がわからないため、保留(※今ここでめっちゃ悩んでる)

・解決手段
わからない

**Comment by youhei0204** [comment]
dockerの設定ファイル見せてくれ
`docker-compose.yml`

**Comment by youhei0204** [comment]
https://qiita.com/obr-note/items/cf737a1d1280e12c9457
こんな記事が出てきた

**Comment by Potepan-sgtom** [comment]
ごめん。質問に答えてなかった。

version: "3"
volumes:
  mysql_data:
  vendor_bundle:
  node_modules:
  public_spree:
  storage:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '33306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  potepanec:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    networks:
      - default
    volumes:
      - .:/potepanec
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /potepanec/log
      - /potepanec/tmp
      - vendor_bundle:/potepanec/vendor/bundle
      - node_modules:/potepanec/node_modules
      - public_spree:/potepanec/public/spree
      - storage:/potepanec/storage
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0
こんな感じ

記事ありがとう！

追記：記事のやつもう試したけどダメだった。

**Comment by Potepan-sgtom** [comment]
引き続き、docker-compose up --build ができない件について

・やりたいことは最初と変わらず

・試したこと
1.上記に加えて、ER図作成のためのbrew install Graphvizを行う(元々gemに入ってるrails-erdがGraphvizに依存しているため)
→その後ER図を出力するため「bundle exec erd --filename=tmp/erd」を入力するも出力されず。(当たり前だけどGraphvizのインストールはできた)
2.ポテパンの質問ボックスで同様の質問を探した時に、docker-compose.ymlに「command: --default-authentication-plugin=mysql_native_password」(文言の意味はわからない)を追加してdocker-compose down --rmi all --volumes --remove-orphans→docker-compose up --buildをすると正常に動作したという記事があったので同じように試したらダメだった。(docker-compose downの時点で上と同じエラーが出る)

・なんとなく問題点
そもそもhomebrewのインストールとdockerをインストールした時点で何を試しても同じエラーが出るので、もうdockerかhomebrewに原因があるとしか思えない。(ポテパンからの指示以外余計なことはしていないので細かいところはわからないけど…)

・逆にこれをやればいけるのではというやつ(もっと理解できないエラーが出ると嫌なのでまだ手をつけてない)
1.dockerをインストールしたもののサインインしていない(Docker Desktop starting...という文字が出ているだけの状態)。
2.エディタを設定していない(vimやAtomなど)→そもそもvscode入れた時点で必要なのかという疑問。
3.solidusについての案内もあったがエディタと同じ理由で正直いらないんじゃないかと思ってノータッチ。
